generic:
  workspace: ./work
  job_command: ./schwefel
  enable_command_argument: False
  batch_job_timeout: 600

resource:
  type: local
  num_node: 4

ABCI:
  group: "[group]"
  job_script_preamble: ./job_script_preamble.sh
  job_execution_options: ""

optimize:
  search_algorithm: aiaccel.optimizer.NelderMeadOptimizer
  goal: minimize
  trial_number: 100
  rand_seed: 42
  parameters:
    -
      name: x1
      type: uniform_float
      lower: -500.0
      upper: 500.0
      initial: 0.0
    -
      name: x2
      type: uniform_float
      lower: -500.0
      upper: 500.0
      initial: 0.0
