generic:
  workspace: ./work
  job_command: python user.py
  python_file: ./user.py
  function: main
  batch_job_timeout: 600
  sleep_time: 0.01
  logging_level: ERROR

resource:
  type: mpi
  num_workers: 1
  mpi_npernode: 2
  mpi_bat_rt_num: 1
  mpi_bat_h_rt: 2:00:00
  mpi_bat_file: ./qsub.sh
  mpi_hostfile: ./hostfile
  mpi_gpu_mode: False
  mpi_bat_make_file: False

ABCI:
  group: your-group-id
  job_execution_options: ""
  job_script_preamble: |
    #!/bin/bash

    #$-l rt_C.small=1
    #$-j y
    #$-cwd

    source /etc/profile.d/modules.sh
    module load gcc/12.2.0
    module load python/3.10/3.10.10

optimize:
  #search_algorithm: "aiaccel.optimizer.NelderMeadOptimizer"
  search_algorithm: "aiaccel.optimizer.RandomOptimizer"
  #search_algorithm: "aiaccel.optimizer.SobolOptimizer"
  #search_algorithm: "aiaccel.optimizer.GridOptimizer"
  #search_algorithm: "aiaccel.optimizer.TpeOptimizer"
  goal: "minimize"
  trial_number: 1
  rand_seed: 42
  parameters:
    -
      name: "x1"
      type: "uniform_float"
      lower: -5.0
      upper: 5.0
    -
      name: "x2"
      type: "uniform_float"
      lower: -5.0
      upper: 5.0
    -
      name: "x3"
      type: "uniform_float"
      lower: -5.0
      upper: 5.0
    -
      name: "x4"
      type: "uniform_float"
      lower: -5.0
      upper: 5.0
    -
      name: "x5"
      type: "uniform_float"
      lower: -5.0
      upper: 5.0
