generic:
  workspace: ./work
  job_command: python user.py
  python_file: ./user.py
  function: main
  enabled_variable_name_argumentation: True
  main_loop_sleep_seconds: 0.01
  logging_level: ERROR

resource:
  type: abci
  # type: local
  # type: python_local
  num_workers: 6

ABCI:
  group: your-group-name
  job_script_preamble: ./job_script_preamble.sh
  job_execution_options: ""

job_setting:
    job_timeout_seconds: 7200
    max_failure_retries: 0
    trial_id_digits: 7

optimize:
  search_algorithm: aiaccel.optimizer.NelderMeadOptimizer
  #search_algorithm: aiaccel.optimizer.RandomOptimizer
  # search_algorithm: aiaccel.optimizer.SobolOptimizer
  # search_algorithm: aiaccel.optimizer.GridOptimizer
  # search_algorithm: aiaccel.optimizer.TpeOptimizer
  goal: minimize
  trial_number: 100
  rand_seed: 42
  parameters:
    -
      name: batch_size
      type: uniform_int
      lower: 64
      upper: 256
      initial: 256
    -
      name: lr
      type: uniform_float
      lower: 1.0e-4
      upper: 1.0
      initial: 0.1
    -
      name: momentum
      type: uniform_float
      lower: 0.8
      upper: 1.0
      initial: 0.9
    -
      name: weight_decay
      type: uniform_float
      lower: 5.0e-6
      upper: 5.0e-2
      initial: 5.0e-4
    -
      name: lr_decay
      type: uniform_float
      lower: 0.0
      upper: 1.0
      initial: 1.0e-3
