generic:
  workspace: ./work
  job_command: python user.py
  python_file: ./user.py
  function: main
  batch_job_timeout: 60
  enabled_variable_name_argumentation: True
  sleep_time: 0.01
  logging_level: INFO

resource:
  # type: abci
  type: local
  #type: python_local
  # type: mpi
  num_workers: 4

ABCI:
  group: your-group-id
  job_execution_options: ""
  job_script_preamble: |
    #!/bin/bash

    #$-l rt_C.small=1
    #$-j y
    #$-cwd

    source /etc/profile.d/modules.sh
    module load gcc/12.2.0
    module load python/3.10/3.10.10

job_setting:
    name_length: 7

optimize:
  search_algorithm: aiaccel.optimizer.ParticleSwarmOptimizer
  goal: minimize
  trial_number: 100
  #rand_seed: 42
  num_particle: 10
  inertia_weight: 0.9
  cognitive_weight: 0.1
  social_weight: 0.1
  parameters:
    -
      name: x1
      type: uniform_float
      lower: 0.0
      upper: 5.0
      #initial: [1.1, 1.2, 1.3, 1.4]
    -
      name: x2
      type: uniform_float
      lower: 0.0
      upper: 5.0
      #initial: [2.1, 2.2, 2.3, 2.4]
